_wandb:
    value:
        cli_version: 0.23.1
        e:
            bi43rh1t7do89biet5v6rkfmwhtb2str:
                args:
                    - --epochs
                    - "10"
                codePath: src\sclera_identity_classification\train.py
                codePathLocal: src\sclera_identity_classification\train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "997001072640"
                        used: "865779400704"
                email: s243873@dtu.dk
                executable: C:\Users\asold\DTU_Local\MLOps\mlops_final_project\.venv\Scripts\python.exe
                git:
                    commit: a185279c19be6577f919d16c8a9ee52e64bb5b81
                    remote: https://github.com/Operators-of-Learning-Machines/mlops_final_project.git
                gpu: NVIDIA GeForce RTX 3050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2048
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Laptop GPU
                      uuid: GPU-e2cddf15-3aa2-a260-6c92-fa4ad8b56e51
                host: Andrei
                memory:
                    total: "16370769920"
                os: Windows-11-10.0.26100-SP0
                program: C:\Users\asold\DTU_Local\MLOps\mlops_final_project\src\sclera_identity_classification\train.py
                python: CPython 3.12.10
                root: C:\Users\asold\DTU_Local\MLOps\mlops_final_project
                startedAt: "2026-01-09T20:11:07.502900Z"
                writerId: bi43rh1t7do89biet5v6rkfmwhtb2str
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 1
                - 2
                - 3
                - 16
            "4": 3.12.10
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
architecture:
    value: squeezenet
batch_size:
    value: 32
channels:
    value: 3
device:
    value: cuda
epochs:
    value: 10
optimizer:
    value: Adam
pretrained:
    value: false
