steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '-f',
    'dockerfiles/train.dockerfile',
    '-t',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/sclera-identity-classification/train:latest',
    '.',
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/sclera-identity-classification/train:latest'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
