defaults:
  - _self_
  - model: null
  - optimizer: null
  - experiment: exp_1 # to change default value, add e.g. experiment=exp_2 to the run cmd
  - wandb: wandb

# disables hydra logging, because we use wandb for logs...
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

epochs: 1
batch_size: 24


# These values are static and should not be changed...:
channels: 3
pretrained: False
gaze_direction: a
saving_period: -1
model_save_path: models/model
model_load_path: null
