name: Deploy Frontend

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}  # Allows manual executions


jobs:
  build-api-image-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        # Authenticate to GCP
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: eternal-lodge-484208-j6

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Build Frontend Docker image
        run: |
          docker build \
            -f dockerfiles/frontend.dockerfile \
            -t sclera-frontend:latest \
            .

      - name: Tag Frontend Docker image
        run: |
          docker tag sclera-frontend:latest \
            europe-west1-docker.pkg.dev/eternal-lodge-484208-j6/sclera-identity-classification/sclera-frontend:latest

      - name: Push Frontend Docker image
        run: |
          docker push europe-west1-docker.pkg.dev/eternal-lodge-484208-j6/sclera-identity-classification/sclera-frontend:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy sclera-frontend \
            --image europe-west1-docker.pkg.dev/eternal-lodge-484208-j6/sclera-identity-classification/sclera-frontend:latest \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated
